"""Update pasword capacityr

Revision ID: 764ff9c4eefd
Revises: b92a146ac72e
Create Date: 2025-05-15 04:16:22.958618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764ff9c4eefd'
down_revision = 'b92a146ac72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
